security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: 'bcrypt'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        public_area:
            pattern: ^/(register|login|public)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: ticket_list
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
